### PR TITLE
Whoops, one more template

### PR DESCRIPTION
**Pull request by deg**
I moved too fast before. Sorry.
I'll have this ready in a few minutes for the other two repos too; just as fast as I can juggle github.

### CODE REVIEW

**Comment by gadfly361** [comment]
Thanks! Can you add this to the other templates you made a PR for as well?

**Comment by deg** [comment]
Yup, working on it now.  Github makes this simple task surprisingly painful, so it will be a couple of minutes per repo.

**Comment by gadfly361** [comment]
Ah gotcha, if you'd prefer, I can go ahead and add them myself.

As an aside, I think these should also be included in the list:

https://github.com/martinklepsch/tenzing
https://github.com/reagent-project/reagent-template

**Comment by deg** [comment]
I just added Chestnut for you.

I’ll add the other two into the comparison spreadsheet (https://goo.gl/ZZH8fm) now.
Can you add them into your READMEs?


By the way, please feel 100% comfortable adding more templates, or any changes or corrections, into the spreadsheet.
I will try to maintain it, but it would be great if the whole community adds to it. I don’t know enough yet about some of the templates.

**Comment by gadfly361** [comment]
@deg Sounds good, thanks again!

**Pull request merged**
