### PR TITLE
Bump library versions

### PR DESCRIPTION
**Pull request by KurtRMueller**
Simple bump to library versions that the re-frame lein template uses.

### CODE REVIEW

**Comment by gadfly361** [comment]
Thanks for keeping track of versions going out of date!  

I'd rather not bump to alpha versions though, so I'll accept if you drop re-frame and re-com, and squash commits. :)

**Comment by mike-thompson-day8** [comment]
Yeah, we're still a week away from official new releases.

**Comment by KurtRMueller** [comment]
So I've never squashed any commit before... what's the easiest way to do this?

**Comment by KurtRMueller** [comment]
I think I squashed correctly? Let me know if anything looks weird.

**Comment by gadfly361** [comment]
Hey Kurt, no worries if you haven't done it before, we'll make it happen.  So currently, there are still two commits.  To squash, I typically do an [interactive rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i).

What you'll want to do, is first check the log.

```
git log
```

In your version of the repo, you should see something like this: 

```
commit cad93a4de457e998fd0abb27227537a911e33cbd
Author: Kurt Mueller <mueller.128@osu.edu>
Date:   Fri Oct 23 13:23:42 2015 -0400

    Bump libraries to latest stable releases.

commit 956aaca18f20c310bac2bceb7a77f46f1d9a9e4c
Author: Kurt Mueller <mueller.128@osu.edu>
Date:   Tue Oct 20 20:04:09 2015 -0400

    Remove whitespace

commit f8ac597d83ac101e7032a39d1885e42b2013d329
Author: Matthew Jaoudi <gadfly361@gmail.com>
Date:   Fri Oct 2 19:28:41 2015 -0700

    Add support for phantomjs 2.0, #10;
```

To start the interactive rebase, we want to decide from what point we are going to start rewriting history from.  In this case, the last commit that is on Day8's version of the repo is the commit "Add support for phantomjs 2.0, #10". To reference this commit, we can use `f8ac597d83ac101e7032a39d1885e42b2013d329`.  So we can do the following:

```
git rebase -i f8ac597d83ac101e7032a39d1885e42b2013d329
```

When you do this, you should see a screen that looks like this:

```
pick 956aaca Remove whitespace
pick cad93a4 Bump libraries to latest stable releases.

# Rebase f8ac597..cad93a4 onto f8ac597 (2 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

You are going to change the first pick to `r` for reword, and the second pick to `s` for squash.  The result should look something like this.

```
r 956aaca Remove whitespace
s cad93a4 Bump libraries to latest stable releases.

...
```

Next you need to save this, and how depends on your default terminal editor.   (This can be tricky, it could be vim or something else, and it isn't entirely intuitive, if you get stuck here, just let me know).  Once you've saved correctly, you'll be brought to a screen to reword the `956aaca` commit.

```
Remove whitespace

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    Kurt Mueller <mueller.128@osu.edu>
# Date:      Tue Oct 20 20:04:09 2015 -0400
#
# rebase in progress; onto f8ac597
# You are currently editing a commit while rebasing branch 'master' on 'f8ac597'.
#
# Changes to be committed:
#       modified:   src/leiningen/new/re_frame/project.clj
#
```

Ok sweet, let's change "Remove whitespace" to something like this:

```
Bump versions of clojure, clojurescript, reagent, and garden to latest stable releases;

# ...
```

Save this, and you should see the following.  (This will end up being the actual commit message that is displayed, anything with a `#` in front is commented).

```
# This is a combination of 2 commits.
# The first commit's message is:

Bump versions of clojure, clojurescript, reagent, and garden to latest stable releases;

# This is the 2nd commit message:

Bump libraries to latest stable releases.

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    Kurt Mueller <mueller.128@osu.edu>
# Date:      Tue Oct 20 20:04:09 2015 -0400
#
# rebase in progress; onto f8ac597
# You are currently editing a commit while rebasing branch 'master' on 'f8ac597'.
#
# Changes to be committed:
#       modified:   src/leiningen/new/re_frame/project.clj
```

However, we don't want to see "Bump libraries to latest stable releases." message anymore, so let's comment it out.

```
# This is a combination of 2 commits.
# The first commit's message is:

Bump versions of clojure, clojurescript, reagent, and garden;

# This is the 2nd commit message:
#
#Bump libraries to latest stable releases.
#
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    Kurt Mueller <mueller.128@osu.edu>
# Date:      Tue Oct 20 20:04:09 2015 -0400
#
# rebase in progress; onto f8ac597
# You are currently editing a commit while rebasing branch 'master' on 'f8ac597'.
#
# Changes to be committed:
#       modified:   src/leiningen/new/re_frame/project.clj
#
```

Save this, and hopefully you will see this in the terminal.

```
[detached HEAD d4c4d07] Remove whitespace
 Author: Kurt Mueller <mueller.128@osu.edu>
 Date: Tue Oct 20 20:04:09 2015 -0400
 1 file changed, 7 insertions(+), 7 deletions(-)
[detached HEAD b666cf6] Bump versions of clojure, clojurescript, reagent, and garden;
 Author: Kurt Mueller <mueller.128@osu.edu>
 Date: Tue Oct 20 20:04:09 2015 -0400
 1 file changed, 6 insertions(+), 6 deletions(-)
Successfully rebased and updated refs/heads/master.
```

Now, all you have to do is push this to your version of the repo.  Since you rewrote history, I anticiapte you will have to do a force push.  So likely need to do something like this:

```
git push origin master -f
```

**Comment by KurtRMueller** [comment]
Alright, should be good to go now.

**Comment by gadfly361** [comment]
No problem, thanks for the PR!

**Pull request merged**
