### PR TITLE
Sass support (via lein-sassc)

### PR DESCRIPTION
**Pull request by polymeris**
Using ~https://github.com/yogthos/lein-sass~ https://github.com/apribase/lein-sassc

Not sure if other people are using sass, but I find myself often adding it manually.

### CODE REVIEW

**Comment by gadfly361** [comment]
@polymeris This is great, thank you!

**Comment by gadfly361** [comment]
@polymeris I decided to revert this PR for the time being, because I merged it prematurely (...my bad). That said, I'd definitely like to get this in.

 The +sass option is dependent on [sassc](https://github.com/sass/sassc) and I am having trouble installing it on linux (see this [issue](https://github.com/sass/sassc/issues/191)).  If we can add some notes in the README on how to get sassc successfully installed on linux, then I am happy to merge again.

**Comment by polymeris** [comment]
As discussed, https://askubuntu.com/questions/566675/how-to-install-node-sass-gulp-sass-on-ubuntu-14-04-or-linux-mint-17/566681#566681

**Comment by polymeris** [comment]
Added a link to [these build instructions](https://github.com/sass/libsass/blob/master/docs/build-with-autotools.md) to README.md with [this commit](https://github.com/polymeris/re-frame-template/commit/dd1e9d283247386dbf0d4c3597f914a72ddd897d)

**Comment by gadfly361** [comment]
@polymeris Thanks again for this PR! We discussed offline a few alternative sass plugins, and I ended up following the lead of [reagent-template](https://github.com/reagent-project/reagent-template) and using [lein-sassy](https://github.com/vladh/lein-sassy).

**Pull request merged**
