### PR TITLE
Add +aliases profile

### PR DESCRIPTION
**Pull request by dundalek**
As discussed in #55.

I noticed `create-templates.sh` seems to be some sort of testing, should I also add the variant with aliases there?

### CODE REVIEW

**Comment by gadfly361** [comment]
@dundalek This looks fantastic!! Thank you so much for opening the issue and submitting this PR :)

Just as a heads up, I plan to cut a new release once I update lein-doo to its newest version ... which should hopefully be sometime soon.

**Comment by gadfly361** [comment]
@dundalek yeah, create-templates.sh is a poor man's version of testing. I'll go ahead and add +aliases there. Thanks again!

**Comment by dundalek** [comment]
@gadfly361 Sweet, thank you for merging and making this great template!

**Comment by gadfly361** [comment]
FYI, just pushed this to clojars

**Pull request merged**
